language: android
jdk: oraclejdk7

android:
  components:
    # Use latest Android SDK tools
    - tools
    - platform-tools
    # Build tools version used to build
    - build-tools-23.0.2
    # Android SDK version used to compile
    - android-16
    # Additional commponents needed for designcompat etc
    - extra-android-m2repository
    - extra-android-support
    - extra-google-m2repository

script:
  - ./gradlew build connectedCheck
